// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'chat.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blake2`, `otpk_address_seed`, `responder_session_from_init`, `spk_secret_from_identity_seed`

/// Generate the device's prekey material: the deterministic SPK
/// (signed) + `opk_count` RANDOM one-time prekeys starting at
/// `opk_start_id`.
Future<DrPrekeySetup> chatDrGenPrekeys({
  required String identitySeedHex,
  required int opkStartId,
  required int opkCount,
}) => RustLib.instance.api.crateChatDrChatDrGenPrekeys(
  identitySeedHex: identitySeedHex,
  opkStartId: opkStartId,
  opkCount: opkCount,
);

/// Publish an OPK bundle to the identity's public prekey mailbox
/// (derived address) through the normal relay send path. Cert-gated
/// like every drop.
Future<ChatSendOutcome> chatDrPublishOpks({
  required String nodeRpc,
  required String identitySeedHex,
  required String opkBundleHex,
  required int totalShares,
  String? authCertThumbprintHex,
  String? authCertSeedHex,
}) => RustLib.instance.api.crateChatDrChatDrPublishOpks(
  nodeRpc: nodeRpc,
  identitySeedHex: identitySeedHex,
  opkBundleHex: opkBundleHex,
  totalShares: totalShares,
  authCertThumbprintHex: authCertThumbprintHex,
  authCertSeedHex: authCertSeedHex,
);

/// Fetch + verify the newest OPK batch from `identity_pubkey_hex`'s
/// public prekey mailbox and pick one. `found = false` (no batch on
/// the relays — expired or never published) is the SPK-only
/// degradation path, not an error.
Future<DrFetchedOpk> chatDrFetchOpk({
  required String nodeRpc,
  required String identityPubkeyHex,
  required List<int> excludeIds,
}) => RustLib.instance.api.crateChatDrChatDrFetchOpk(
  nodeRpc: nodeRpc,
  identityPubkeyHex: identityPubkeyHex,
  excludeIds: excludeIds,
);

/// Start a new conversation: verify the recipient's published SPK,
/// run full X3DH (with the OPK if one was fetched), and return the
/// initiator session + the X3dhInit to attach to the FIRST
/// `chat_send`.
Future<DrInitiation> chatDrInitiate({
  required String identitySeedHex,
  required String recipientIdentityPubkeyHex,
  required String recipientSpkHex,
  required String recipientSpkSignatureHex,
  int? opkId,
  String? opkPubkeyHex,
}) => RustLib.instance.api.crateChatDrChatDrInitiate(
  identitySeedHex: identitySeedHex,
  recipientIdentityPubkeyHex: recipientIdentityPubkeyHex,
  recipientSpkHex: recipientSpkHex,
  recipientSpkSignatureHex: recipientSpkSignatureHex,
  opkId: opkId,
  opkPubkeyHex: opkPubkeyHex,
);

/// An OPK picked from a fetched, signature-verified batch.
class DrFetchedOpk {
  final bool found;
  final int id;
  final String pubkeyHex;

  const DrFetchedOpk({
    required this.found,
    required this.id,
    required this.pubkeyHex,
  });

  @override
  int get hashCode => found.hashCode ^ id.hashCode ^ pubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrFetchedOpk &&
          runtimeType == other.runtimeType &&
          found == other.found &&
          id == other.id &&
          pubkeyHex == other.pubkeyHex;
}

/// A ready-to-send conversation bootstrap: pass `session_state_hex`
/// and `x3dh_init_hex` to the first `chat_send`.
class DrInitiation {
  final String sessionStateHex;
  final String x3DhInitHex;

  const DrInitiation({
    required this.sessionStateHex,
    required this.x3DhInitHex,
  });

  @override
  int get hashCode => sessionStateHex.hashCode ^ x3DhInitHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrInitiation &&
          runtimeType == other.runtimeType &&
          sessionStateHex == other.sessionStateHex &&
          x3DhInitHex == other.x3DhInitHex;
}

/// A stored one-time-prekey secret.
class DrOpkSecret {
  final int id;
  final String secretHex;

  const DrOpkSecret({required this.id, required this.secretHex});

  @override
  int get hashCode => id.hashCode ^ secretHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrOpkSecret &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          secretHex == other.secretHex;
}

/// Output of [`chat_dr_gen_prekeys`]. `spk_*` go into the RNS record
/// (via `chat_publish_identity`); `opk_bundle_hex` is published with
/// [`chat_dr_publish_opks`]; `opk_secrets` MUST be stored by the app
/// (encrypted) — each is consumed by the first inbound conversation
/// that used it.
class DrPrekeySetup {
  final String spkPubkeyHex;
  final String spkSignatureHex;
  final String opkBundleHex;
  final List<DrOpkSecret> opkSecrets;

  const DrPrekeySetup({
    required this.spkPubkeyHex,
    required this.spkSignatureHex,
    required this.opkBundleHex,
    required this.opkSecrets,
  });

  @override
  int get hashCode =>
      spkPubkeyHex.hashCode ^
      spkSignatureHex.hashCode ^
      opkBundleHex.hashCode ^
      opkSecrets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrPrekeySetup &&
          runtimeType == other.runtimeType &&
          spkPubkeyHex == other.spkPubkeyHex &&
          spkSignatureHex == other.spkSignatureHex &&
          opkBundleHex == other.opkBundleHex &&
          opkSecrets == other.opkSecrets;
}
