// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_session_nonce`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChatAuthenticateResultRpc`, `ChatNodeInfoRpc`, `HeaderRpc`

/// Generate a fresh software Ed25519 session keypair. The dart layer
/// persists `seed_hex` (encrypted) for the session's lifetime and re-derives
/// the signing key per drop; it never touches the secure element.
Future<ChatSessionKeypair> chatSessionGenKeypair() =>
    RustLib.instance.api.crateChatSessionChatSessionGenKeypair();

/// Read the guard's identity (`chat_nodeInfo`) and a recent block, then derive
/// the handshake nonce. The caller feeds `nonce_hex` to the hardware HIP
/// ceremony as the attestation challenge before calling
/// [`chat_session_authenticate`].
Future<ChatSessionPrepared> chatSessionPrepare({
  required String nodeRpc,
  required String certThumbprintHex,
  required String sessionPubkeyHex,
}) => RustLib.instance.api.crateChatSessionChatSessionPrepare(
  nodeRpc: nodeRpc,
  certThumbprintHex: certThumbprintHex,
  sessionPubkeyHex: sessionPubkeyHex,
);

/// Submit the HIP proof to the node's `chat_authenticate`, establishing the
/// session. `hip_proof_hex` is the SCALE-encoded `CanonicalHipProof` produced
/// by the hardware ceremony with `prepare`'s nonce baked in; `anchor_block_number`
/// is the value from [`chat_session_prepare`].
Future<ChatSessionOutcome> chatSessionAuthenticate({
  required String nodeRpc,
  required String certThumbprintHex,
  required String hipProofHex,
  required BigInt anchorBlockNumber,
  required String sessionPubkeyHex,
}) => RustLib.instance.api.crateChatSessionChatSessionAuthenticate(
  nodeRpc: nodeRpc,
  certThumbprintHex: certThumbprintHex,
  hipProofHex: hipProofHex,
  anchorBlockNumber: anchorBlockNumber,
  sessionPubkeyHex: sessionPubkeyHex,
);

/// Sign an onion packet with the session key for `chat_send_onion`'s session
/// path. Returns the 64-byte Ed25519 signature (hex) over
/// `blake2_256(CHAT_SESSION_DROP_DOMAIN ‖ packet)`. Pure software — no
/// secure-element crossing, no biometric (the handshake already proved those).
Future<String> chatSessionSignDrop({
  required String sessionSeedHex,
  required String onionPacketHex,
}) => RustLib.instance.api.crateChatSessionChatSessionSignDrop(
  sessionSeedHex: sessionSeedHex,
  onionPacketHex: onionPacketHex,
);

/// A fresh software session keypair. The seed stays on-device (ordinary
/// app storage — NOT the secure element); the pubkey is authorized by the
/// handshake and stored by the node to verify per-drop signatures.
class ChatSessionKeypair {
  final String seedHex;
  final String pubkeyHex;

  const ChatSessionKeypair({required this.seedHex, required this.pubkeyHex});

  @override
  int get hashCode => seedHex.hashCode ^ pubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatSessionKeypair &&
          runtimeType == other.runtimeType &&
          seedHex == other.seedHex &&
          pubkeyHex == other.pubkeyHex;
}

/// Outcome of a successful handshake. The session is now live at the node
/// until `expiry_unix_secs`; the client should pin this node and re-handshake
/// proactively (≈80% of `session_ttl_secs`) and on any node switch.
class ChatSessionOutcome {
  final String boundAccountHex;
  final BigInt expiryUnixSecs;
  final BigInt sessionTtlSecs;

  const ChatSessionOutcome({
    required this.boundAccountHex,
    required this.expiryUnixSecs,
    required this.sessionTtlSecs,
  });

  @override
  int get hashCode =>
      boundAccountHex.hashCode ^
      expiryUnixSecs.hashCode ^
      sessionTtlSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatSessionOutcome &&
          runtimeType == other.runtimeType &&
          boundAccountHex == other.boundAccountHex &&
          expiryUnixSecs == other.expiryUnixSecs &&
          sessionTtlSecs == other.sessionTtlSecs;
}

/// Inputs the client must gather (and the nonce it must derive) before the
/// hardware HIP step. `nonce_hex` is fed to the StrongBox/TPM attestation
/// challenge so the resulting proof is bound to this exact (block, cert,
/// guard, session-key) tuple.
class ChatSessionPrepared {
  /// The recent block the nonce is anchored to (sent to the node so it can
  /// re-derive the same nonce against the same block hash).
  final BigInt anchorBlockNumber;
  final String anchorBlockHashHex;

  /// The guard node's Ed25519 identity (binds the handshake to this node).
  final String guardNodeIdHex;

  /// The nonce to bake into the HIP attestation challenge.
  final String nonceHex;

  const ChatSessionPrepared({
    required this.anchorBlockNumber,
    required this.anchorBlockHashHex,
    required this.guardNodeIdHex,
    required this.nonceHex,
  });

  @override
  int get hashCode =>
      anchorBlockNumber.hashCode ^
      anchorBlockHashHex.hashCode ^
      guardNodeIdHex.hashCode ^
      nonceHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatSessionPrepared &&
          runtimeType == other.runtimeType &&
          anchorBlockNumber == other.anchorBlockNumber &&
          anchorBlockHashHex == other.anchorBlockHashHex &&
          guardNodeIdHex == other.guardNodeIdHex &&
          nonceHex == other.nonceHex;
}
