// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_hex32`, `identity_from_seed`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChatFetchedShareRaw`, `ChatSendResultRpc`, `ChatShareDescriptorRpc`, `InnerPayload`

/// Derive a chat identity from a deterministic 32-byte seed (hex).
ChatIdentity chatGenIdentity({required String seedHex}) =>
    RustLib.instance.api.crateChatChatGenIdentity(seedHex: seedHex);

/// Build + sign + sealed-sender-seal a pairwise message on-device, then
/// dispatch it through the named node via `chat_send_envelope`.
///
/// `auth_thumbprint_hex` / `auth_timestamp_secs` / `auth_sig_hex` are
/// the cert-auth seam: pass `None` for the node's v0.1 demo path, or
/// real values once HW-attested cert signing is wired.
Future<ChatSendOutcome> chatSend({
  required String nodeRpc,
  required String senderSeedHex,
  required String recipientPubkeyHex,
  required String message,
  required String senderName,
  required int totalShares,
  String? authThumbprintHex,
  BigInt? authTimestampSecs,
  String? authSigHex,
}) => RustLib.instance.api.crateChatChatSend(
  nodeRpc: nodeRpc,
  senderSeedHex: senderSeedHex,
  recipientPubkeyHex: recipientPubkeyHex,
  message: message,
  senderName: senderName,
  totalShares: totalShares,
  authThumbprintHex: authThumbprintHex,
  authTimestampSecs: authTimestampSecs,
  authSigHex: authSigHex,
);

/// Fetch shares for the recipient, then reconstruct + unseal + verify
/// any complete message stripes on-device. Returns the recovered,
/// sender-verified messages.
Future<List<RecoveredMessage>> chatFetch({
  required String nodeRpc,
  required String recipientSeedHex,
  String? relayPeer,
}) => RustLib.instance.api.crateChatChatFetch(
  nodeRpc: nodeRpc,
  recipientSeedHex: recipientSeedHex,
  relayPeer: relayPeer,
);

/// Public keys + pickup key derived from a chat-identity seed. The two
/// parties exchange the Ed25519 pubkey out-of-band (or via RNS) so each
/// can address the other.
class ChatIdentity {
  final String ed25519PubkeyHex;
  final String x25519PubkeyHex;
  final String pickupKeyHex;

  const ChatIdentity({
    required this.ed25519PubkeyHex,
    required this.x25519PubkeyHex,
    required this.pickupKeyHex,
  });

  @override
  int get hashCode =>
      ed25519PubkeyHex.hashCode ^
      x25519PubkeyHex.hashCode ^
      pickupKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatIdentity &&
          runtimeType == other.runtimeType &&
          ed25519PubkeyHex == other.ed25519PubkeyHex &&
          x25519PubkeyHex == other.x25519PubkeyHex &&
          pickupKeyHex == other.pickupKeyHex;
}

/// Outcome of a successful `chat_send_envelope` dispatch.
class ChatSendOutcome {
  final String messageIdHex;
  final int shareCount;
  final String recipientPickupKeyHex;

  const ChatSendOutcome({
    required this.messageIdHex,
    required this.shareCount,
    required this.recipientPickupKeyHex,
  });

  @override
  int get hashCode =>
      messageIdHex.hashCode ^
      shareCount.hashCode ^
      recipientPickupKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatSendOutcome &&
          runtimeType == other.runtimeType &&
          messageIdHex == other.messageIdHex &&
          shareCount == other.shareCount &&
          recipientPickupKeyHex == other.recipientPickupKeyHex;
}

/// A message reconstructed, unsealed and sender-verified on-device.
class RecoveredMessage {
  final String messageIdHex;

  /// The verified sender chat-identity Ed25519 pubkey (hex).
  final String senderPubkeyHex;

  /// The sender's CLAIMED `.rst` name (empty if none). UNVERIFIED here — the
  /// caller forward-resolves it and checks it maps to `sender_pubkey_hex`.
  final String claimedSenderName;

  /// UTF-8 plaintext if the body decodes as UTF-8, else empty.
  final String plaintext;

  /// Raw recovered body, always present.
  final String plaintextHex;

  const RecoveredMessage({
    required this.messageIdHex,
    required this.senderPubkeyHex,
    required this.claimedSenderName,
    required this.plaintext,
    required this.plaintextHex,
  });

  @override
  int get hashCode =>
      messageIdHex.hashCode ^
      senderPubkeyHex.hashCode ^
      claimedSenderName.hashCode ^
      plaintext.hashCode ^
      plaintextHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveredMessage &&
          runtimeType == other.runtimeType &&
          messageIdHex == other.messageIdHex &&
          senderPubkeyHex == other.senderPubkeyHex &&
          claimedSenderName == other.claimedSenderName &&
          plaintext == other.plaintext &&
          plaintextHex == other.plaintextHex;
}
