// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Sr25519Signer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `account_id`, `sign`

Future<String> fetchBalance({
  required String address,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreFetchBalance(
  address: address,
  rpcUrl: rpcUrl,
);

Future<NameAvailability> checkNameAvailability({
  required String name,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreCheckNameAvailability(
  name: name,
  rpcUrl: rpcUrl,
);

Future<String?> resolveAddressToName({
  required String address,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreResolveAddressToName(
  address: address,
  rpcUrl: rpcUrl,
);

Future<NameListing?> getNameListing({
  required String name,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreGetNameListing(name: name, rpcUrl: rpcUrl);

Future<ResolvedName?> resolveNameVerified({
  required String name,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreResolveNameVerified(
  name: name,
  rpcUrl: rpcUrl,
);

Future<bool> verifyNameOwnership({
  required String name,
  required String blockHashHex,
  required String expectedOwner,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreVerifyNameOwnership(
  name: name,
  blockHashHex: blockHashHex,
  expectedOwner: expectedOwner,
  rpcUrl: rpcUrl,
);

Future<String> sendDot({
  required String toAddress,
  required String amountPlanck,
  required String phrase,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreSendDot(
  toAddress: toAddress,
  amountPlanck: amountPlanck,
  phrase: phrase,
  rpcUrl: rpcUrl,
);

Future<String> buyName({
  required String name,
  required String phrase,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreBuyName(
  name: name,
  phrase: phrase,
  rpcUrl: rpcUrl,
);

Future<String> getNamePrice({required String name, required String rpcUrl}) =>
    RustLib.instance.api.crateCoreGetNamePrice(name: name, rpcUrl: rpcUrl);

Future<String> registerName({
  required String name,
  required String phrase,
  required String rpcUrl,
}) => RustLib.instance.api.crateCoreRegisterName(
  name: name,
  phrase: phrase,
  rpcUrl: rpcUrl,
);

(DotAccount, String) generateAccount() =>
    RustLib.instance.api.crateCoreGenerateAccount();

DotAccount restoreAccount({required String phrase}) =>
    RustLib.instance.api.crateCoreRestoreAccount(phrase: phrase);

Uint8List encryptPhrase({required String phrase, required String passphrase}) =>
    RustLib.instance.api.crateCoreEncryptPhrase(
      phrase: phrase,
      passphrase: passphrase,
    );

String decryptPhrase({required List<int> blob, required String passphrase}) =>
    RustLib.instance.api.crateCoreDecryptPhrase(
      blob: blob,
      passphrase: passphrase,
    );

PassphraseStrength checkPassphraseStrength({required String passphrase}) =>
    RustLib.instance.api.crateCoreCheckPassphraseStrength(
      passphrase: passphrase,
    );

class DotAccount {
  final String address;
  final Uint8List publicKey;

  const DotAccount({required this.address, required this.publicKey});

  @override
  int get hashCode => address.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DotAccount &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          publicKey == other.publicKey;
}

class NameAvailability {
  final bool available;
  final bool forSale;

  const NameAvailability({required this.available, required this.forSale});

  @override
  int get hashCode => available.hashCode ^ forSale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NameAvailability &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          forSale == other.forSale;
}

class NameListing {
  final String price;
  final String seller;

  const NameListing({required this.price, required this.seller});

  @override
  int get hashCode => price.hashCode ^ seller.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NameListing &&
          runtimeType == other.runtimeType &&
          price == other.price &&
          seller == other.seller;
}

class PassphraseStrength {
  final int score;
  final String? warning;
  final List<String> suggestions;
  final double guessesLog10;

  const PassphraseStrength({
    required this.score,
    this.warning,
    required this.suggestions,
    required this.guessesLog10,
  });

  @override
  int get hashCode =>
      score.hashCode ^
      warning.hashCode ^
      suggestions.hashCode ^
      guessesLog10.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassphraseStrength &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          warning == other.warning &&
          suggestions == other.suggestions &&
          guessesLog10 == other.guessesLog10;
}

class ResolvedName {
  final String owner;
  final int lastBlock;
  final String blockHash;

  const ResolvedName({
    required this.owner,
    required this.lastBlock,
    required this.blockHash,
  });

  @override
  int get hashCode => owner.hashCode ^ lastBlock.hashCode ^ blockHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedName &&
          runtimeType == other.runtimeType &&
          owner == other.owner &&
          lastBlock == other.lastBlock &&
          blockHash == other.blockHash;
}
