// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(DotAccount, String) generateAccount() =>
    RustLib.instance.api.crateCoreGenerateAccount();

DotAccount restoreAccount({required String phrase}) =>
    RustLib.instance.api.crateCoreRestoreAccount(phrase: phrase);

Uint8List encryptPhrase({required String phrase, required String passphrase}) =>
    RustLib.instance.api.crateCoreEncryptPhrase(
      phrase: phrase,
      passphrase: passphrase,
    );

String decryptPhrase({required List<int> blob, required String passphrase}) =>
    RustLib.instance.api.crateCoreDecryptPhrase(
      blob: blob,
      passphrase: passphrase,
    );

PassphraseStrength checkPassphraseStrength({required String passphrase}) =>
    RustLib.instance.api.crateCoreCheckPassphraseStrength(
      passphrase: passphrase,
    );

class DotAccount {
  final String address;
  final Uint8List publicKey;

  const DotAccount({required this.address, required this.publicKey});

  @override
  int get hashCode => address.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DotAccount &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          publicKey == other.publicKey;
}

class PassphraseStrength {
  final int score;
  final String? warning;
  final List<String> suggestions;
  final double guessesLog10;

  const PassphraseStrength({
    required this.score,
    this.warning,
    required this.suggestions,
    required this.guessesLog10,
  });

  @override
  int get hashCode =>
      score.hashCode ^
      warning.hashCode ^
      suggestions.hashCode ^
      guessesLog10.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassphraseStrength &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          warning == other.warning &&
          suggestions == other.suggestions &&
          guessesLog10 == other.guessesLog10;
}
