// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'core.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  NameListing dco_decode_box_autoadd_name_listing(dynamic raw);

  @protected
  ResolvedName dco_decode_box_autoadd_resolved_name(dynamic raw);

  @protected
  DotAccount dco_decode_dot_account(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NameAvailability dco_decode_name_availability(dynamic raw);

  @protected
  NameListing dco_decode_name_listing(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  NameListing? dco_decode_opt_box_autoadd_name_listing(dynamic raw);

  @protected
  ResolvedName? dco_decode_opt_box_autoadd_resolved_name(dynamic raw);

  @protected
  PassphraseStrength dco_decode_passphrase_strength(dynamic raw);

  @protected
  (DotAccount, String) dco_decode_record_dot_account_string(dynamic raw);

  @protected
  ResolvedName dco_decode_resolved_name(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  NameListing sse_decode_box_autoadd_name_listing(SseDeserializer deserializer);

  @protected
  ResolvedName sse_decode_box_autoadd_resolved_name(
    SseDeserializer deserializer,
  );

  @protected
  DotAccount sse_decode_dot_account(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NameAvailability sse_decode_name_availability(SseDeserializer deserializer);

  @protected
  NameListing sse_decode_name_listing(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  NameListing? sse_decode_opt_box_autoadd_name_listing(
    SseDeserializer deserializer,
  );

  @protected
  ResolvedName? sse_decode_opt_box_autoadd_resolved_name(
    SseDeserializer deserializer,
  );

  @protected
  PassphraseStrength sse_decode_passphrase_strength(
    SseDeserializer deserializer,
  );

  @protected
  (DotAccount, String) sse_decode_record_dot_account_string(
    SseDeserializer deserializer,
  );

  @protected
  ResolvedName sse_decode_resolved_name(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_name_listing(
    NameListing self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resolved_name(
    ResolvedName self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dot_account(DotAccount self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_name_availability(
    NameAvailability self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_name_listing(NameListing self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_name_listing(
    NameListing? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_resolved_name(
    ResolvedName? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_passphrase_strength(
    PassphraseStrength self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_dot_account_string(
    (DotAccount, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resolved_name(ResolvedName self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
