// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'core.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1065598670;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_core',
        ioDirectory: 'rust_core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateCoreBuyName({
    required String name,
    required String phrase,
    required String rpcUrl,
  });

  Future<NameAvailability> crateCoreCheckNameAvailability({
    required String name,
    required String rpcUrl,
  });

  PassphraseStrength crateCoreCheckPassphraseStrength({
    required String passphrase,
  });

  String crateCoreDecryptPhrase({
    required List<int> blob,
    required String passphrase,
  });

  Uint8List crateCoreEncryptPhrase({
    required String phrase,
    required String passphrase,
  });

  Future<String> crateCoreFetchBalance({
    required String address,
    required String rpcUrl,
  });

  (DotAccount, String) crateCoreGenerateAccount();

  Future<NameListing?> crateCoreGetNameListing({
    required String name,
    required String rpcUrl,
  });

  Future<String> crateCoreGetNamePrice({
    required String name,
    required String rpcUrl,
  });

  Future<String> crateCoreRegisterName({
    required String name,
    required String phrase,
    required String rpcUrl,
  });

  Future<String?> crateCoreResolveAddressToName({
    required String address,
    required String rpcUrl,
  });

  Future<ResolvedName?> crateCoreResolveNameVerified({
    required String name,
    required String rpcUrl,
  });

  DotAccount crateCoreRestoreAccount({required String phrase});

  Future<String> crateCoreSendDot({
    required String toAddress,
    required String amountPlanck,
    required String phrase,
    required String rpcUrl,
  });

  Future<bool> crateCoreVerifyNameOwnership({
    required String name,
    required String blockHashHex,
    required String expectedOwner,
    required String rpcUrl,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateCoreBuyName({
    required String name,
    required String phrase,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(phrase, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreBuyNameConstMeta,
        argValues: [name, phrase, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreBuyNameConstMeta => const TaskConstMeta(
    debugName: "buy_name",
    argNames: ["name", "phrase", "rpcUrl"],
  );

  @override
  Future<NameAvailability> crateCoreCheckNameAvailability({
    required String name,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_name_availability,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreCheckNameAvailabilityConstMeta,
        argValues: [name, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreCheckNameAvailabilityConstMeta =>
      const TaskConstMeta(
        debugName: "check_name_availability",
        argNames: ["name", "rpcUrl"],
      );

  @override
  PassphraseStrength crateCoreCheckPassphraseStrength({
    required String passphrase,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passphrase, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_passphrase_strength,
          decodeErrorData: null,
        ),
        constMeta: kCrateCoreCheckPassphraseStrengthConstMeta,
        argValues: [passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreCheckPassphraseStrengthConstMeta =>
      const TaskConstMeta(
        debugName: "check_passphrase_strength",
        argNames: ["passphrase"],
      );

  @override
  String crateCoreDecryptPhrase({
    required List<int> blob,
    required String passphrase,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(blob, serializer);
          sse_encode_String(passphrase, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreDecryptPhraseConstMeta,
        argValues: [blob, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreDecryptPhraseConstMeta => const TaskConstMeta(
    debugName: "decrypt_phrase",
    argNames: ["blob", "passphrase"],
  );

  @override
  Uint8List crateCoreEncryptPhrase({
    required String phrase,
    required String passphrase,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          sse_encode_String(passphrase, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreEncryptPhraseConstMeta,
        argValues: [phrase, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreEncryptPhraseConstMeta => const TaskConstMeta(
    debugName: "encrypt_phrase",
    argNames: ["phrase", "passphrase"],
  );

  @override
  Future<String> crateCoreFetchBalance({
    required String address,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateCoreFetchBalanceConstMeta,
        argValues: [address, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreFetchBalanceConstMeta => const TaskConstMeta(
    debugName: "fetch_balance",
    argNames: ["address", "rpcUrl"],
  );

  @override
  (DotAccount, String) crateCoreGenerateAccount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_dot_account_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateCoreGenerateAccountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreGenerateAccountConstMeta =>
      const TaskConstMeta(debugName: "generate_account", argNames: []);

  @override
  Future<NameListing?> crateCoreGetNameListing({
    required String name,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_name_listing,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreGetNameListingConstMeta,
        argValues: [name, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreGetNameListingConstMeta => const TaskConstMeta(
    debugName: "get_name_listing",
    argNames: ["name", "rpcUrl"],
  );

  @override
  Future<String> crateCoreGetNamePrice({
    required String name,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreGetNamePriceConstMeta,
        argValues: [name, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreGetNamePriceConstMeta => const TaskConstMeta(
    debugName: "get_name_price",
    argNames: ["name", "rpcUrl"],
  );

  @override
  Future<String> crateCoreRegisterName({
    required String name,
    required String phrase,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(phrase, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreRegisterNameConstMeta,
        argValues: [name, phrase, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreRegisterNameConstMeta => const TaskConstMeta(
    debugName: "register_name",
    argNames: ["name", "phrase", "rpcUrl"],
  );

  @override
  Future<String?> crateCoreResolveAddressToName({
    required String address,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreResolveAddressToNameConstMeta,
        argValues: [address, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreResolveAddressToNameConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_address_to_name",
        argNames: ["address", "rpcUrl"],
      );

  @override
  Future<ResolvedName?> crateCoreResolveNameVerified({
    required String name,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_resolved_name,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreResolveNameVerifiedConstMeta,
        argValues: [name, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreResolveNameVerifiedConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_name_verified",
        argNames: ["name", "rpcUrl"],
      );

  @override
  DotAccount crateCoreRestoreAccount({required String phrase}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dot_account,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreRestoreAccountConstMeta,
        argValues: [phrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreRestoreAccountConstMeta =>
      const TaskConstMeta(debugName: "restore_account", argNames: ["phrase"]);

  @override
  Future<String> crateCoreSendDot({
    required String toAddress,
    required String amountPlanck,
    required String phrase,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toAddress, serializer);
          sse_encode_String(amountPlanck, serializer);
          sse_encode_String(phrase, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreSendDotConstMeta,
        argValues: [toAddress, amountPlanck, phrase, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreSendDotConstMeta => const TaskConstMeta(
    debugName: "send_dot",
    argNames: ["toAddress", "amountPlanck", "phrase", "rpcUrl"],
  );

  @override
  Future<bool> crateCoreVerifyNameOwnership({
    required String name,
    required String blockHashHex,
    required String expectedOwner,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(blockHashHex, serializer);
          sse_encode_String(expectedOwner, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateCoreVerifyNameOwnershipConstMeta,
        argValues: [name, blockHashHex, expectedOwner, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCoreVerifyNameOwnershipConstMeta =>
      const TaskConstMeta(
        debugName: "verify_name_ownership",
        argNames: ["name", "blockHashHex", "expectedOwner", "rpcUrl"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  NameListing dco_decode_box_autoadd_name_listing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_name_listing(raw);
  }

  @protected
  ResolvedName dco_decode_box_autoadd_resolved_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_resolved_name(raw);
  }

  @protected
  DotAccount dco_decode_dot_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DotAccount(
      address: dco_decode_String(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NameAvailability dco_decode_name_availability(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NameAvailability(
      available: dco_decode_bool(arr[0]),
      forSale: dco_decode_bool(arr[1]),
    );
  }

  @protected
  NameListing dco_decode_name_listing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NameListing(
      price: dco_decode_String(arr[0]),
      seller: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  NameListing? dco_decode_opt_box_autoadd_name_listing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_name_listing(raw);
  }

  @protected
  ResolvedName? dco_decode_opt_box_autoadd_resolved_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_resolved_name(raw);
  }

  @protected
  PassphraseStrength dco_decode_passphrase_strength(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PassphraseStrength(
      score: dco_decode_u_8(arr[0]),
      warning: dco_decode_opt_String(arr[1]),
      suggestions: dco_decode_list_String(arr[2]),
      guessesLog10: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  (DotAccount, String) dco_decode_record_dot_account_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_dot_account(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  ResolvedName dco_decode_resolved_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ResolvedName(
      owner: dco_decode_String(arr[0]),
      lastBlock: dco_decode_u_32(arr[1]),
      blockHash: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  NameListing sse_decode_box_autoadd_name_listing(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_name_listing(deserializer));
  }

  @protected
  ResolvedName sse_decode_box_autoadd_resolved_name(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_resolved_name(deserializer));
  }

  @protected
  DotAccount sse_decode_dot_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return DotAccount(address: var_address, publicKey: var_publicKey);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NameAvailability sse_decode_name_availability(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_available = sse_decode_bool(deserializer);
    var var_forSale = sse_decode_bool(deserializer);
    return NameAvailability(available: var_available, forSale: var_forSale);
  }

  @protected
  NameListing sse_decode_name_listing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_price = sse_decode_String(deserializer);
    var var_seller = sse_decode_String(deserializer);
    return NameListing(price: var_price, seller: var_seller);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NameListing? sse_decode_opt_box_autoadd_name_listing(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_name_listing(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ResolvedName? sse_decode_opt_box_autoadd_resolved_name(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_resolved_name(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PassphraseStrength sse_decode_passphrase_strength(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_score = sse_decode_u_8(deserializer);
    var var_warning = sse_decode_opt_String(deserializer);
    var var_suggestions = sse_decode_list_String(deserializer);
    var var_guessesLog10 = sse_decode_f_64(deserializer);
    return PassphraseStrength(
      score: var_score,
      warning: var_warning,
      suggestions: var_suggestions,
      guessesLog10: var_guessesLog10,
    );
  }

  @protected
  (DotAccount, String) sse_decode_record_dot_account_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_dot_account(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  ResolvedName sse_decode_resolved_name(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_owner = sse_decode_String(deserializer);
    var var_lastBlock = sse_decode_u_32(deserializer);
    var var_blockHash = sse_decode_String(deserializer);
    return ResolvedName(
      owner: var_owner,
      lastBlock: var_lastBlock,
      blockHash: var_blockHash,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_name_listing(
    NameListing self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_name_listing(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_resolved_name(
    ResolvedName self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_resolved_name(self, serializer);
  }

  @protected
  void sse_encode_dot_account(DotAccount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_name_availability(
    NameAvailability self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.available, serializer);
    sse_encode_bool(self.forSale, serializer);
  }

  @protected
  void sse_encode_name_listing(NameListing self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.price, serializer);
    sse_encode_String(self.seller, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_name_listing(
    NameListing? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_name_listing(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_resolved_name(
    ResolvedName? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_resolved_name(self, serializer);
    }
  }

  @protected
  void sse_encode_passphrase_strength(
    PassphraseStrength self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.score, serializer);
    sse_encode_opt_String(self.warning, serializer);
    sse_encode_list_String(self.suggestions, serializer);
    sse_encode_f_64(self.guessesLog10, serializer);
  }

  @protected
  void sse_encode_record_dot_account_string(
    (DotAccount, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dot_account(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_resolved_name(ResolvedName self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.owner, serializer);
    sse_encode_u_32(self.lastBlock, serializer);
    sse_encode_String(self.blockHash, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
