// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'core.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'mime_wrap_client.dart';
import 'mime_wrap_prover.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'personhood.dart';
import 'totp_enrollment.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountDashboardInfo dco_decode_account_dashboard_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  LivenessInputsFields dco_decode_box_autoadd_liveness_inputs_fields(
    dynamic raw,
  );

  @protected
  NameListing dco_decode_box_autoadd_name_listing(dynamic raw);

  @protected
  PassportInputsFields dco_decode_box_autoadd_passport_inputs_fields(
    dynamic raw,
  );

  @protected
  PopCertInfo dco_decode_box_autoadd_pop_cert_info(dynamic raw);

  @protected
  ResolvedName dco_decode_box_autoadd_resolved_name(dynamic raw);

  @protected
  StrongBoxCeremonyBundle dco_decode_box_autoadd_strong_box_ceremony_bundle(
    dynamic raw,
  );

  @protected
  DnsRecord dco_decode_dns_record(dynamic raw);

  @protected
  DotAccount dco_decode_dot_account(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DnsRecord> dco_decode_list_dns_record(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LivenessInputsFields dco_decode_liveness_inputs_fields(dynamic raw);

  @protected
  MimeWrapProofBenchmark dco_decode_mime_wrap_proof_benchmark(dynamic raw);

  @protected
  MimeWrapProofResult dco_decode_mime_wrap_proof_result(dynamic raw);

  @protected
  MimeWrapSetupResult dco_decode_mime_wrap_setup_result(dynamic raw);

  @protected
  NameAvailability dco_decode_name_availability(dynamic raw);

  @protected
  NameListing dco_decode_name_listing(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  NameListing? dco_decode_opt_box_autoadd_name_listing(dynamic raw);

  @protected
  PopCertInfo? dco_decode_opt_box_autoadd_pop_cert_info(dynamic raw);

  @protected
  ResolvedName? dco_decode_opt_box_autoadd_resolved_name(dynamic raw);

  @protected
  OsAttestation dco_decode_os_attestation(dynamic raw);

  @protected
  PassphraseStrength dco_decode_passphrase_strength(dynamic raw);

  @protected
  PassportInputsFields dco_decode_passport_inputs_fields(dynamic raw);

  @protected
  PopCertInfo dco_decode_pop_cert_info(dynamic raw);

  @protected
  (DotAccount, String) dco_decode_record_dot_account_string(dynamic raw);

  @protected
  ResolvedName dco_decode_resolved_name(dynamic raw);

  @protected
  StrongBoxCeremonyBundle dco_decode_strong_box_ceremony_bundle(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountDashboardInfo sse_decode_account_dashboard_info(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  LivenessInputsFields sse_decode_box_autoadd_liveness_inputs_fields(
    SseDeserializer deserializer,
  );

  @protected
  NameListing sse_decode_box_autoadd_name_listing(SseDeserializer deserializer);

  @protected
  PassportInputsFields sse_decode_box_autoadd_passport_inputs_fields(
    SseDeserializer deserializer,
  );

  @protected
  PopCertInfo sse_decode_box_autoadd_pop_cert_info(
    SseDeserializer deserializer,
  );

  @protected
  ResolvedName sse_decode_box_autoadd_resolved_name(
    SseDeserializer deserializer,
  );

  @protected
  StrongBoxCeremonyBundle sse_decode_box_autoadd_strong_box_ceremony_bundle(
    SseDeserializer deserializer,
  );

  @protected
  DnsRecord sse_decode_dns_record(SseDeserializer deserializer);

  @protected
  DotAccount sse_decode_dot_account(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DnsRecord> sse_decode_list_dns_record(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LivenessInputsFields sse_decode_liveness_inputs_fields(
    SseDeserializer deserializer,
  );

  @protected
  MimeWrapProofBenchmark sse_decode_mime_wrap_proof_benchmark(
    SseDeserializer deserializer,
  );

  @protected
  MimeWrapProofResult sse_decode_mime_wrap_proof_result(
    SseDeserializer deserializer,
  );

  @protected
  MimeWrapSetupResult sse_decode_mime_wrap_setup_result(
    SseDeserializer deserializer,
  );

  @protected
  NameAvailability sse_decode_name_availability(SseDeserializer deserializer);

  @protected
  NameListing sse_decode_name_listing(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  NameListing? sse_decode_opt_box_autoadd_name_listing(
    SseDeserializer deserializer,
  );

  @protected
  PopCertInfo? sse_decode_opt_box_autoadd_pop_cert_info(
    SseDeserializer deserializer,
  );

  @protected
  ResolvedName? sse_decode_opt_box_autoadd_resolved_name(
    SseDeserializer deserializer,
  );

  @protected
  OsAttestation sse_decode_os_attestation(SseDeserializer deserializer);

  @protected
  PassphraseStrength sse_decode_passphrase_strength(
    SseDeserializer deserializer,
  );

  @protected
  PassportInputsFields sse_decode_passport_inputs_fields(
    SseDeserializer deserializer,
  );

  @protected
  PopCertInfo sse_decode_pop_cert_info(SseDeserializer deserializer);

  @protected
  (DotAccount, String) sse_decode_record_dot_account_string(
    SseDeserializer deserializer,
  );

  @protected
  ResolvedName sse_decode_resolved_name(SseDeserializer deserializer);

  @protected
  StrongBoxCeremonyBundle sse_decode_strong_box_ceremony_bundle(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_dashboard_info(
    AccountDashboardInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_liveness_inputs_fields(
    LivenessInputsFields self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_name_listing(
    NameListing self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_passport_inputs_fields(
    PassportInputsFields self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pop_cert_info(
    PopCertInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resolved_name(
    ResolvedName self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_strong_box_ceremony_bundle(
    StrongBoxCeremonyBundle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dns_record(DnsRecord self, SseSerializer serializer);

  @protected
  void sse_encode_dot_account(DotAccount self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dns_record(
    List<DnsRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_liveness_inputs_fields(
    LivenessInputsFields self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mime_wrap_proof_benchmark(
    MimeWrapProofBenchmark self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mime_wrap_proof_result(
    MimeWrapProofResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mime_wrap_setup_result(
    MimeWrapSetupResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_name_availability(
    NameAvailability self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_name_listing(NameListing self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_name_listing(
    NameListing? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pop_cert_info(
    PopCertInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_resolved_name(
    ResolvedName? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_os_attestation(OsAttestation self, SseSerializer serializer);

  @protected
  void sse_encode_passphrase_strength(
    PassphraseStrength self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_passport_inputs_fields(
    PassportInputsFields self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pop_cert_info(PopCertInfo self, SseSerializer serializer);

  @protected
  void sse_encode_record_dot_account_string(
    (DotAccount, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resolved_name(ResolvedName self, SseSerializer serializer);

  @protected
  void sse_encode_strong_box_ceremony_bundle(
    StrongBoxCeremonyBundle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
