// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_witness`, `zkpki_state_call`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FetchedWitness`, `MembershipWitnessDataScale`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `lab_witness_check`, `verify_id_binding`

/// The fixed public point `W` performs its in-chip ECDH against, as
/// 65-byte uncompressed SEC1 (`0x04 || X || Y`) — the encoding Android
/// Keystore's `KeyAgreement` peer expects. Deterministic: derived fresh
/// on every call via RFC 9380 hash-to-curve and pinned by a KAT below.
Future<Uint8List> membershipPFixedSec1() =>
    RustLib.instance.api.crateMembershipMembershipPFixedSec1();

/// Reduce the in-chip ECDH shared secret to the member secret `s` and
/// return `id_commitment = Poseidon(s)` as canonical little-endian hex.
///
/// The shared secret is zeroized before returning. `s` itself never
/// leaves this function; callers that need `s` again (the per-epoch
/// handshake proof) re-run the in-chip ECDH.
Future<String> membershipIdCommitment({required String sharedSecretHex}) =>
    RustLib.instance.api.crateMembershipMembershipIdCommitment(
      sharedSecretHex: sharedSecretHex,
    );

/// The 32-byte message attest_ec signs for chat enrollment:
/// `blake2_256(ID_BINDING_CONTEXT || id_commitment || challenge)`.
/// `challenge` is the offer nonce (`contract_nonce`) — the same bytes
/// `mint_cert` passes to `verify_chat_enrollment` on-chain.
Future<String> membershipIdBindingMsg({
  required String idCommitmentHex,
  required String challengeHex,
}) => RustLib.instance.api.crateMembershipMembershipIdBindingMsg(
  idCommitmentHex: idCommitmentHex,
  challengeHex: challengeHex,
);

/// M3 FRB surface (also the labtool `witness-check` gate): fetch the real
/// Merkle witness for `thumbprint` and reconstruct the chain roots locally.
/// `shared_secret_hex` is the in-chip ECDH output (the same bytes the mint
/// enrollment used) — needed to re-derive the leaf's `id_commitment`.
Future<MembershipWitness> membershipFetchWitness({
  required String chainRpc,
  required String thumbprintHex,
  required String sharedSecretHex,
}) => RustLib.instance.api.crateMembershipMembershipFetchWitness(
  chainRpc: chainRpc,
  thumbprintHex: thumbprintHex,
  sharedSecretHex: sharedSecretHex,
);

/// Find the caller's chat-ENROLLED cert: iterate `CertsByUser(account)`
/// (Blake2_128Concat keys, so each raw key's last 32 bytes ARE the
/// thumbprint) and return the first whose `membership_witness` exists.
/// `None` = the account holds no enrolled cert, so membership auth is
/// unavailable and callers should not burn a biometric trying.
///
/// This lookup exists because an account can hold certs WITHOUT a chat
/// enrollment (the app's dev admission cert, certs minted before the
/// feature): the send path's cert is not necessarily the enrolled one.
Future<String?> membershipEnrolledThumbprint({
  required String chainRpc,
  required String accountSs58,
}) => RustLib.instance.api.crateMembershipMembershipEnrolledThumbprint(
  chainRpc: chainRpc,
  accountSs58: accountSs58,
);

/// M4: the real membership handshake. Re-derives `s` from the in-chip ECDH
/// output, fetches the REAL chain witness for the cert's leaf, proves
/// membership on-device (Groth16), and POSTs `chat_authenticateMembership`
/// to the guard. On success the guard's witnessed-spend committee has
/// co-signed the nullifier spend and the returned session key is authorized
/// for drops until `expires_epoch`.
///
/// Fails fast (before proving, which costs ~1s) if the locally recomputed
/// roots don't match the chain's — a mismatch means the leaf/witness are
/// inconsistent and the guard would reject the proof anyway.
Future<MembershipSessionOutcome> membershipAuthenticate({
  required String chainRpc,
  required String guardRpc,
  required String thumbprintHex,
  required String sharedSecretHex,
  required List<int> pkBytes,
}) => RustLib.instance.api.crateMembershipMembershipAuthenticate(
  chainRpc: chainRpc,
  guardRpc: guardRpc,
  thumbprintHex: thumbprintHex,
  sharedSecretHex: sharedSecretHex,
  pkBytes: pkBytes,
);

/// The anonymous membership session (M4): what the phone holds after a
/// successful `chat_authenticateMembership`. `session_seed_hex` is the
/// software Ed25519 seed that signs each drop (`chat_session_sign_drop`);
/// `session_pubkey_hex` doubles as the send path's session lookup key.
class MembershipSessionOutcome {
  final String sessionPubkeyHex;
  final String sessionSeedHex;
  final BigInt expiresEpoch;
  final BigInt currentEpoch;
  final String nullifierHex;
  final String guardNodeIdHex;

  const MembershipSessionOutcome({
    required this.sessionPubkeyHex,
    required this.sessionSeedHex,
    required this.expiresEpoch,
    required this.currentEpoch,
    required this.nullifierHex,
    required this.guardNodeIdHex,
  });

  @override
  int get hashCode =>
      sessionPubkeyHex.hashCode ^
      sessionSeedHex.hashCode ^
      expiresEpoch.hashCode ^
      currentEpoch.hashCode ^
      nullifierHex.hashCode ^
      guardNodeIdHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MembershipSessionOutcome &&
          runtimeType == other.runtimeType &&
          sessionPubkeyHex == other.sessionPubkeyHex &&
          sessionSeedHex == other.sessionSeedHex &&
          expiresEpoch == other.expiresEpoch &&
          currentEpoch == other.currentEpoch &&
          nullifierHex == other.nullifierHex &&
          guardNodeIdHex == other.guardNodeIdHex;
}

/// The cert's membership witness, fetched from the chain and verified
/// locally: `root_matches` says the root recomputed from
/// `leaf(id_commitment, expiry, scope)` + the returned path equals the
/// chain's `membership_root()` (and likewise for the freshness tree).
class MembershipWitness {
  final BigInt leafPosition;
  final BigInt expiryBlock;
  final int freshUntilEpoch;
  final BigInt scope;
  final BigInt currentEpoch;
  final BigInt bestBlock;
  final String localMembershipRootHex;
  final String chainMembershipRootHex;
  final String localFreshnessRootHex;
  final String chainFreshnessRootHex;
  final bool rootMatches;

  const MembershipWitness({
    required this.leafPosition,
    required this.expiryBlock,
    required this.freshUntilEpoch,
    required this.scope,
    required this.currentEpoch,
    required this.bestBlock,
    required this.localMembershipRootHex,
    required this.chainMembershipRootHex,
    required this.localFreshnessRootHex,
    required this.chainFreshnessRootHex,
    required this.rootMatches,
  });

  @override
  int get hashCode =>
      leafPosition.hashCode ^
      expiryBlock.hashCode ^
      freshUntilEpoch.hashCode ^
      scope.hashCode ^
      currentEpoch.hashCode ^
      bestBlock.hashCode ^
      localMembershipRootHex.hashCode ^
      chainMembershipRootHex.hashCode ^
      localFreshnessRootHex.hashCode ^
      chainFreshnessRootHex.hashCode ^
      rootMatches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MembershipWitness &&
          runtimeType == other.runtimeType &&
          leafPosition == other.leafPosition &&
          expiryBlock == other.expiryBlock &&
          freshUntilEpoch == other.freshUntilEpoch &&
          scope == other.scope &&
          currentEpoch == other.currentEpoch &&
          bestBlock == other.bestBlock &&
          localMembershipRootHex == other.localMembershipRootHex &&
          chainMembershipRootHex == other.chainMembershipRootHex &&
          localFreshnessRootHex == other.localFreshnessRootHex &&
          chainFreshnessRootHex == other.chainFreshnessRootHex &&
          rootMatches == other.rootMatches;
}
