// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bits_from_bytes_be`, `load_or_cache_zkey`, `random_bytes`, `run_benchmark`, `sha256_concat`

/// Generate a random-fixture Groth16 proof for the mime_wrap circuit
/// and return end-to-end timing. Inputs are the absolute paths to:
///
///  - `wasm_path`  — Circom wasm for witness generation
///  - `r1cs_path`  — Circom r1cs (circuit structure)
///  - `zkey_path`  — Groth16 proving key
///
/// Paths must be absolute file paths on the device's filesystem. The
/// Kotlin side is responsible for copying the Android assets to
/// `context.filesDir` and passing the resulting paths here — this
/// module does not touch Android APIs.
Future<MimeWrapProofBenchmark> benchmarkMimeWrapProof({
  required String wasmPath,
  required String r1CsPath,
  required String zkeyPath,
}) => RustLib.instance.api.crateMimeWrapProverBenchmarkMimeWrapProof(
  wasmPath: wasmPath,
  r1CsPath: r1CsPath,
  zkeyPath: zkeyPath,
);

/// Benchmark result surfaced to Dart via flutter_rust_bridge. All
/// timing fields are milliseconds. `success` is `false` when any step
/// of the pipeline errored; `error_message` then carries the Rust-side
/// `Display` string.
///
/// `zkey_cache_hit` distinguishes the "cold" (first call, key parse
/// included) vs "warm" (cached key) path. Only the warm number is a
/// real measure of per-sign latency.
class MimeWrapProofBenchmark {
  final bool success;
  final String? errorMessage;
  final int zkeyLoadMs;
  final bool zkeyCacheHit;
  final int witnessGenMs;
  final int proofGenMs;
  final int totalMs;
  final Uint8List proofBytes;
  final int publicInputsCount;

  const MimeWrapProofBenchmark({
    required this.success,
    this.errorMessage,
    required this.zkeyLoadMs,
    required this.zkeyCacheHit,
    required this.witnessGenMs,
    required this.proofGenMs,
    required this.totalMs,
    required this.proofBytes,
    required this.publicInputsCount,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      errorMessage.hashCode ^
      zkeyLoadMs.hashCode ^
      zkeyCacheHit.hashCode ^
      witnessGenMs.hashCode ^
      proofGenMs.hashCode ^
      totalMs.hashCode ^
      proofBytes.hashCode ^
      publicInputsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MimeWrapProofBenchmark &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          zkeyLoadMs == other.zkeyLoadMs &&
          zkeyCacheHit == other.zkeyCacheHit &&
          witnessGenMs == other.witnessGenMs &&
          proofGenMs == other.proofGenMs &&
          totalMs == other.totalMs &&
          proofBytes == other.proofBytes &&
          publicInputsCount == other.publicInputsCount;
}
