// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bits_from_bytes_be`, `build_setup`, `hex_encode`, `run_generate`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedSetup`

/// Run the one-time trusted setup for the mime_wrap circuit and
/// return the compressed verifying key hex. Idempotent — subsequent
/// calls return the cached vk without re-running setup.
Future<MimeWrapSetupResult> prepareMimeWrapSetup({
  required String wasmPath,
  required String r1CsPath,
}) => RustLib.instance.api.crateMimeWrapClientPrepareMimeWrapSetup(
  wasmPath: wasmPath,
  r1CsPath: r1CsPath,
);

/// Compute the ceremony-time commitment `C = SHA256(ec_key_pub || seed)`.
/// Must match byte-for-byte what the pallet's `verify_and_record` expects
/// to see — same sha2 crate, same concatenation order as the Circom
/// C1 constraint and the pallet's `build_public_inputs`.
Future<Uint8List> computeCommitment({
  required List<int> ecKeyPub,
  required List<int> seed,
}) => RustLib.instance.api.crateMimeWrapClientComputeCommitment(
  ecKeyPub: ecKeyPub,
  seed: seed,
);

/// Generate a mime_wrap Groth16 proof for real ceremony state.
///
/// Inputs must match the Circom circuit's expectations bit-for-bit:
///  - `ec_key_pub`, `seed`: 32 bytes each
///  - `bucket`: u64, big-endian inside the circuit
///  - `user_otp`: low-24-bits (24 bits total, big-endian)
///
/// The caller is responsible for matching these against on-chain state
/// (the registered commitment + the bucket/otp being claimed). A proof
/// generated with mismatching inputs will deserialize fine but fail the
/// pairing check at the pallet.
///
/// Requires `prepare_mime_wrap_setup` to have been called at least
/// once (populates the PK cache). Returns an error if the cache is
/// empty.
Future<MimeWrapProofResult> generateMimeWrapSigningProof({
  required String wasmPath,
  required String r1CsPath,
  required List<int> ecKeyPub,
  required List<int> seed,
  required BigInt bucket,
  required int userOtp,
}) => RustLib.instance.api.crateMimeWrapClientGenerateMimeWrapSigningProof(
  wasmPath: wasmPath,
  r1CsPath: r1CsPath,
  ecKeyPub: ecKeyPub,
  seed: seed,
  bucket: bucket,
  userOtp: userOtp,
);

/// Convenience for the Dart side: SHA256 the raw DER-SPKI cert_ec pubkey
/// (91 bytes from Stage 0 ceremony) to get the 32-byte ec_key_pub
/// representative the circuit expects.
Future<Uint8List> deriveEcKeyPubFromDer({required List<int> der}) =>
    RustLib.instance.api.crateMimeWrapClientDeriveEcKeyPubFromDer(der: der);

class MimeWrapProofResult {
  final bool success;
  final String? errorMessage;
  final String proofBytesHex;
  final int totalMs;

  const MimeWrapProofResult({
    required this.success,
    this.errorMessage,
    required this.proofBytesHex,
    required this.totalMs,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      errorMessage.hashCode ^
      proofBytesHex.hashCode ^
      totalMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MimeWrapProofResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          proofBytesHex == other.proofBytesHex &&
          totalMs == other.totalMs;
}

/// Shape surfaced to Dart from the one-time setup call. `vk_bytes_hex`
/// is the compressed Groth16 VK that Tony installs on rostro-node via
/// sudo `set_verifying_key` (one-time, per chain).
class MimeWrapSetupResult {
  final bool success;
  final String? errorMessage;
  final String vkBytesHex;

  /// If true, this call actually ran circuit_specific_setup (~30-60s
  /// on S20). If false, the cache was already populated — call
  /// returns in ms.
  final bool freshSetup;
  final int setupMs;

  const MimeWrapSetupResult({
    required this.success,
    this.errorMessage,
    required this.vkBytesHex,
    required this.freshSetup,
    required this.setupMs,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      errorMessage.hashCode ^
      vkBytesHex.hashCode ^
      freshSetup.hashCode ^
      setupMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MimeWrapSetupResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          vkBytesHex == other.vkBytesHex &&
          freshSetup == other.freshSetup &&
          setupMs == other.setupMs;
}
