// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'core.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chain_anchor_value`, `liveness_inputs_value`, `passport_inputs_value`, `strongbox_hip_proof_value`, `submit_personhood_call`

/// Atomic single-extrinsic PoP mint. Caller signs with the same SS58
/// the proofs are bound to. The pallet enforces:
/// (a) no existing PoP cert for this account, (b) HIP attestation
/// fresh and AIK-bound, (c) cross-proof binding (matching dg2_hash and
/// anchor), (d) chain anchor freshness, (e) trust roots match current,
/// (f) passport not expired, (g) nullifier not consumed,
/// (h) both Groth16 proofs verify.
Future<String> submitMintPop({
  required String passportProofHex,
  required PassportInputsFields passportInputs,
  required String livenessProofHex,
  required LivenessInputsFields livenessInputs,
  required String hwCertThumbprintHex,
  required StrongBoxCeremonyBundle hipBundle,
  required String phrase,
  required String rpcUrl,
}) => RustLib.instance.api.cratePersonhoodSubmitMintPop(
  passportProofHex: passportProofHex,
  passportInputs: passportInputs,
  livenessProofHex: livenessProofHex,
  livenessInputs: livenessInputs,
  hwCertThumbprintHex: hwCertThumbprintHex,
  hipBundle: hipBundle,
  phrase: phrase,
  rpcUrl: rpcUrl,
);

/// Caller destroys their own PoP cert. Frees the nullifier so the same
/// passport may re-mint to a different SS58 (or after passport renewal
/// produces a new MRZ → new nullifier).
Future<String> submitDiscardPop({
  required String phrase,
  required String rpcUrl,
}) => RustLib.instance.api.cratePersonhoodSubmitDiscardPop(
  phrase: phrase,
  rpcUrl: rpcUrl,
);

/// SRT-only: rotate the CSCA bundle merkle root. Same extrinsic for
/// first-publish post-genesis, scheduled quarterly rotation, and
/// emergency rotation; SRT decides pacing operationally. Hard cutover
/// (no grace window) — see memory `feedback_dont_kick_can_with_grace_windows`.
Future<String> submitSrtSetCscaRoot({
  required String newRootHex,
  required String phrase,
  required String rpcUrl,
}) => RustLib.instance.api.cratePersonhoodSubmitSrtSetCscaRoot(
  newRootHex: newRootHex,
  phrase: phrase,
  rpcUrl: rpcUrl,
);

/// SRT-only: rotate the seats mapping merkle root. Existing PoP certs
/// grandfather their stored `seat_id`; only new mints see the new root.
Future<String> submitSrtSetSeatsRoot({
  required String newRootHex,
  required String phrase,
  required String rpcUrl,
}) => RustLib.instance.api.cratePersonhoodSubmitSrtSetSeatsRoot(
  newRootHex: newRootHex,
  phrase: phrase,
  rpcUrl: rpcUrl,
);

/// SRT-only: rotate the verifying key for one of the two circuits.
/// `which` is `"PassportAttest"` or `"LivenessFacematch"`. Strict
/// monotonic — `new_version` MUST equal `prev_version + 1` (rollback to
/// a known-good earlier set is performed by re-running the ceremony
/// with the desired bytes and the next monotonic version).
Future<String> submitSrtSetVk({
  required String which,
  required String newVkBytesHex,
  required int newVersion,
  required String ceremonyHashHex,
  required String phrase,
  required String rpcUrl,
}) => RustLib.instance.api.cratePersonhoodSubmitSrtSetVk(
  which: which,
  newVkBytesHex: newVkBytesHex,
  newVersion: newVersion,
  ceremonyHashHex: ceremonyHashHex,
  phrase: phrase,
  rpcUrl: rpcUrl,
);

/// Look up the PoP cert record for an account. Returns `Ok(None)` if
/// the account has no cert. Uses `rostro-client` (the read path that
/// replaced subxt for storage queries) — see `crate::rostro_client`.
Future<PopCertInfo?> queryPopCert({
  required String account,
  required String rpcUrl,
}) => RustLib.instance.api.cratePersonhoodQueryPopCert(
  account: account,
  rpcUrl: rpcUrl,
);

/// Public-input bundle for the `liveness_facematch` circuit.
class LivenessInputsFields {
  /// 32-byte hex. Must equal the paired passport_attest's `dg2_hash`.
  final String dg2HashHex;

  /// SS58 the proof binds to. Must match the signer.
  final String boundAccount;
  final bool livenessPassed;

  /// Same chain anchor block as the paired passport_attest proof.
  final int anchorBlock;
  final String anchorHashHex;

  const LivenessInputsFields({
    required this.dg2HashHex,
    required this.boundAccount,
    required this.livenessPassed,
    required this.anchorBlock,
    required this.anchorHashHex,
  });

  @override
  int get hashCode =>
      dg2HashHex.hashCode ^
      boundAccount.hashCode ^
      livenessPassed.hashCode ^
      anchorBlock.hashCode ^
      anchorHashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivenessInputsFields &&
          runtimeType == other.runtimeType &&
          dg2HashHex == other.dg2HashHex &&
          boundAccount == other.boundAccount &&
          livenessPassed == other.livenessPassed &&
          anchorBlock == other.anchorBlock &&
          anchorHashHex == other.anchorHashHex;
}

/// Public-input bundle for the `passport_attest` circuit, in
/// hex-string / primitive form for FFI.
class PassportInputsFields {
  /// `Poseidon(MRZ_canonical, ROSTRO_POP_DOMAIN)` — 32-byte hex.
  final String nullifierHex;

  /// SS58 the proof binds to. Must match the signer.
  final String boundAccount;

  /// Passport expiry expressed in chain block-number form.
  final int ttlBlock;

  /// `(anchor_block - dob_block) >= 18_years_in_blocks`.
  final bool adult;

  /// Country resolved through the seats merkle tree (country code stays
  /// private, only seat_id reveals).
  final int seatId;

  /// Recent chain anchor's block number.
  final int anchorBlock;

  /// 32-byte hex of the chain block hash at `anchor_block`.
  final String anchorHashHex;

  /// 32-byte hex of the CSCA bundle merkle root the proof was generated against.
  final String cscaRootHex;

  /// 32-byte hex of the seats mapping merkle root the proof was generated against.
  final String seatsRootHex;

  /// 32-byte hex of the chip's DG2 (photo) hash. Cross-proof binding to
  /// the liveness_facematch proof.
  final String dg2HashHex;

  const PassportInputsFields({
    required this.nullifierHex,
    required this.boundAccount,
    required this.ttlBlock,
    required this.adult,
    required this.seatId,
    required this.anchorBlock,
    required this.anchorHashHex,
    required this.cscaRootHex,
    required this.seatsRootHex,
    required this.dg2HashHex,
  });

  @override
  int get hashCode =>
      nullifierHex.hashCode ^
      boundAccount.hashCode ^
      ttlBlock.hashCode ^
      adult.hashCode ^
      seatId.hashCode ^
      anchorBlock.hashCode ^
      anchorHashHex.hashCode ^
      cscaRootHex.hashCode ^
      seatsRootHex.hashCode ^
      dg2HashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassportInputsFields &&
          runtimeType == other.runtimeType &&
          nullifierHex == other.nullifierHex &&
          boundAccount == other.boundAccount &&
          ttlBlock == other.ttlBlock &&
          adult == other.adult &&
          seatId == other.seatId &&
          anchorBlock == other.anchorBlock &&
          anchorHashHex == other.anchorHashHex &&
          cscaRootHex == other.cscaRootHex &&
          seatsRootHex == other.seatsRootHex &&
          dg2HashHex == other.dg2HashHex;
}

/// Returned by [`query_pop_cert`]. Mirrors the on-chain `PopCert<u32>`
/// shape with hex-encoded byte fields for FFI ergonomics.
class PopCertInfo {
  final String nullifierHex;
  final int ttlBlock;
  final bool adult;
  final int seatId;
  final int mintedAt;

  const PopCertInfo({
    required this.nullifierHex,
    required this.ttlBlock,
    required this.adult,
    required this.seatId,
    required this.mintedAt,
  });

  @override
  int get hashCode =>
      nullifierHex.hashCode ^
      ttlBlock.hashCode ^
      adult.hashCode ^
      seatId.hashCode ^
      mintedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PopCertInfo &&
          runtimeType == other.runtimeType &&
          nullifierHex == other.nullifierHex &&
          ttlBlock == other.ttlBlock &&
          adult == other.adult &&
          seatId == other.seatId &&
          mintedAt == other.mintedAt;
}
