// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate 20 bytes of cryptographically secure entropy for TOTP seed.
///
/// The returned bytes are handed to JNI immediately for StrongBox import,
/// then zeroized by the caller. They must never be stored in Dart state,
/// SharedPreferences, or any persistent storage.
///
/// Uses `ring::rand::SystemRandom` (backed by OS CSPRNG).
/// The memory region is locked via `mlock` to prevent swapping to disk.
Uint8List generateTotpSeedProtected() =>
    RustLib.instance.api.crateTotpEnrollmentGenerateTotpSeedProtected();

/// Build an otpauth:// URI for QR code display.
///
/// The URI encodes the TOTP parameters for any standard authenticator app:
/// Google Authenticator, Authy, Microsoft Authenticator, etc.
///
/// Uses HMAC-SHA256 (not SHA1) to match StrongBox's HMAC capability.
/// 6-digit codes, 30-second period.
///
/// The seed bytes are zeroized internally after Base32 encoding.
/// The Base32 string is zeroized after URI construction.
/// The returned URI string contains the Base32 secret — display it once,
/// then discard. Never persist it.
String buildOtpauthUri({required List<int> seed, required String username}) =>
    RustLib.instance.api.crateTotpEnrollmentBuildOtpauthUri(
      seed: seed,
      username: username,
    );

/// Explicitly zeroize a byte vector.
///
/// Called from Flutter/Dart after any sensitive operation to ensure
/// byte arrays don't linger in memory. The bridge copies data across
/// the FFI boundary, so both sides must zeroize independently.
void zeroizeBytes({required List<int> data}) =>
    RustLib.instance.api.crateTotpEnrollmentZeroizeBytes(data: data);
