// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `best_block`, `block_on`, `connect`, `label`, `label`, `label`, `label`, `summary_to_ffi`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AttestationTypeScale`, `CertStateScale`, `CertStatusResponseScale`, `CertSummaryScale`, `EkuScale`, `EntityStateScale`, `OcspStatusScale`, `PopRequirementScale`, `RevocationReasonScale`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`

/// All certs bound to `address` (any issuer, any template), newest mint
/// first, plus the best block for countdown rendering.
Future<CertListFfi> zkpkiCertsByUser({
  required String chainRpc,
  required String address,
}) => RustLib.instance.api.crateZkpkiCertsZkpkiCertsByUser(
  chainRpc: chainRpc,
  address: address,
);

/// Full trust-context status for one cert. Errors with "cert not found"
/// when the chain has no record of the thumbprint (purged / never existed).
Future<CertStatusFfi> zkpkiCertStatus({
  required String chainRpc,
  required String thumbprintHex,
}) => RustLib.instance.api.crateZkpkiCertsZkpkiCertStatus(
  chainRpc: chainRpc,
  thumbprintHex: thumbprintHex,
);

/// The My Certs list plus the best block it was read at, so the UI can
/// render expiry countdowns without a second round trip.
class CertListFfi {
  final BigInt bestBlock;
  final List<CertSummaryFfi> certs;

  const CertListFfi({required this.bestBlock, required this.certs});

  @override
  int get hashCode => bestBlock.hashCode ^ certs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CertListFfi &&
          runtimeType == other.runtimeType &&
          bestBlock == other.bestBlock &&
          certs == other.certs;
}

/// Full detail for one cert (detail screen).
class CertStatusFfi {
  final String thumbprintHex;

  /// "Good" | "Revoked" (OCSP layer).
  final String ocspStatus;

  /// Current block at response time.
  final BigInt thisUpdate;
  final BigInt? revocationTime;
  final String? revocationReason;
  final String state;
  final bool isActive;
  final BigInt expiryBlock;
  final BigInt mintBlock;
  final String issuerSs58;
  final String issuerStatus;
  final String rootSs58;
  final String rootStatus;
  final String attestationType;
  final bool manufacturerVerified;
  final String templateName;
  final bool? popRequired;

  /// The complete EKU catalog with per-entry `held` flags.
  final List<EkuFlagFfi> ekus;

  /// True iff the cert holds the ProofOfPersonhood EKU — a PoP
  /// *credential*, distinct from the template's mint-time PoP
  /// mechanism requirement (`pop_required`).
  final bool hasPersonhood;

  /// True iff the cert holds the ChatAuth EKU (⇔ a live membership
  /// leaf, by the mint-time stamping invariant).
  final bool hasChatAuth;

  const CertStatusFfi({
    required this.thumbprintHex,
    required this.ocspStatus,
    required this.thisUpdate,
    this.revocationTime,
    this.revocationReason,
    required this.state,
    required this.isActive,
    required this.expiryBlock,
    required this.mintBlock,
    required this.issuerSs58,
    required this.issuerStatus,
    required this.rootSs58,
    required this.rootStatus,
    required this.attestationType,
    required this.manufacturerVerified,
    required this.templateName,
    this.popRequired,
    required this.ekus,
    required this.hasPersonhood,
    required this.hasChatAuth,
  });

  @override
  int get hashCode =>
      thumbprintHex.hashCode ^
      ocspStatus.hashCode ^
      thisUpdate.hashCode ^
      revocationTime.hashCode ^
      revocationReason.hashCode ^
      state.hashCode ^
      isActive.hashCode ^
      expiryBlock.hashCode ^
      mintBlock.hashCode ^
      issuerSs58.hashCode ^
      issuerStatus.hashCode ^
      rootSs58.hashCode ^
      rootStatus.hashCode ^
      attestationType.hashCode ^
      manufacturerVerified.hashCode ^
      templateName.hashCode ^
      popRequired.hashCode ^
      ekus.hashCode ^
      hasPersonhood.hashCode ^
      hasChatAuth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CertStatusFfi &&
          runtimeType == other.runtimeType &&
          thumbprintHex == other.thumbprintHex &&
          ocspStatus == other.ocspStatus &&
          thisUpdate == other.thisUpdate &&
          revocationTime == other.revocationTime &&
          revocationReason == other.revocationReason &&
          state == other.state &&
          isActive == other.isActive &&
          expiryBlock == other.expiryBlock &&
          mintBlock == other.mintBlock &&
          issuerSs58 == other.issuerSs58 &&
          issuerStatus == other.issuerStatus &&
          rootSs58 == other.rootSs58 &&
          rootStatus == other.rootStatus &&
          attestationType == other.attestationType &&
          manufacturerVerified == other.manufacturerVerified &&
          templateName == other.templateName &&
          popRequired == other.popRequired &&
          ekus == other.ekus &&
          hasPersonhood == other.hasPersonhood &&
          hasChatAuth == other.hasChatAuth;
}

/// One row of the My Certs list.
class CertSummaryFfi {
  final String thumbprintHex;

  /// "Active" | "Suspended" | "Expired" | "Purged" (display string).
  final String state;
  final bool isActive;
  final BigInt expiryBlock;
  final BigInt mintBlock;
  final String attestationType;
  final bool manufacturerVerified;

  /// Cert carries the ChatAuth EKU — the declared (EKU ⇔ leaf)
  /// form of "may authenticate to chat guards". Replaces the old
  /// per-cert membership_witness probe for list badging.
  final bool chatAuth;

  const CertSummaryFfi({
    required this.thumbprintHex,
    required this.state,
    required this.isActive,
    required this.expiryBlock,
    required this.mintBlock,
    required this.attestationType,
    required this.manufacturerVerified,
    required this.chatAuth,
  });

  @override
  int get hashCode =>
      thumbprintHex.hashCode ^
      state.hashCode ^
      isActive.hashCode ^
      expiryBlock.hashCode ^
      mintBlock.hashCode ^
      attestationType.hashCode ^
      manufacturerVerified.hashCode ^
      chatAuth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CertSummaryFfi &&
          runtimeType == other.runtimeType &&
          thumbprintHex == other.thumbprintHex &&
          state == other.state &&
          isActive == other.isActive &&
          expiryBlock == other.expiryBlock &&
          mintBlock == other.mintBlock &&
          attestationType == other.attestationType &&
          manufacturerVerified == other.manufacturerVerified &&
          chatAuth == other.chatAuth;
}

/// One entry of the full EKU catalog: `held` marks capabilities this
/// cert actually carries (rendered as read-only checked boxes).
class EkuFlagFfi {
  final String label;
  final bool held;

  const EkuFlagFfi({required this.label, required this.held});

  @override
  int get hashCode => label.hashCode ^ held.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EkuFlagFfi &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          held == other.held;
}
